apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-client-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-client-app
  template:
    metadata:
      labels:
        app: node-client-app
    spec:
      containers:
      - name: node-client-app
        image: rotua10/node-client_app:latest  # Ganti dengan nama Docker Hub Anda
        ports:
        - containerPort: 3000
        env:
        - name: DB_HOST
          value: "db"
        - name: DB_USER
          value: "user"
        - name: DB_PASS
          value: "root"
        - name: DB_NAME
          value: "Wayang Tales"
