apiVersion: v1
kind: Service
metadata:
  name: node-client-app-service
spec:
  selector:
    app: node-client-app
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: NodePort
